controllers:
    resource: ../src/Controller/
    type: attribute

# ACCUEIL
accueil:
    path: /accueil
    controller: App\Controller\BailController::index

# AJOUTER BAIL
ajouterBail:
    path: /baux/ajouter
    controller: App\Controller\BailController::ajouterBail

# LISTER BAUX
bauxLister:
    path: /baux/lister
    controller: App\Controller\BailController::listerBaux

# LISTER BAUX ARCHIVES
bauxArchivesLister:
    path: /baux/listerBauxArchives
    controller: App\Controller\BailController::listerBauxArchives

# CONSULTER BAUX
bauxConsulter:
    path: /baux/consulter/{id}
    controller: App\Controller\BailController::consulterBaux

# LISTER PAIEMENT
paiementLister:
    path: /paiement/listerLoyer
    controller: App\Controller\PaiementController::listerLoyer

# LISTER MOUVEMENT
mouvementLister:
    path: /mouvement/lister
    controller: App\Controller\MouvementController::listerMouvement

# UPLOAD FILE MOUVEMENT
mouvementUploadFile:
    path: /mouvement/uploadFile
    controller: App\Controller\MouvementController::uploadFileMouvement

# MODIFIER MOUVEMENT
modifierMouvement:
    path: /mouvement/modifier/{id}
    controller: App\Controller\MouvementController::modifierMouvement

# PDF QUITTANCE
quittancePDF:
    path: /baux/{id}/quittance
    controller: App\Controller\BailController::quittancePDF

# CONSULTER APPARTEMENT
appartementConsulter:
    path: /appartement/consulter/{id}
    controller: App\Controller\AppartementController::consulterAppartement

# LISTER CONTRAT DE LOCATION
contratLocationLister:
    path: /baux/listerContratLocation
    controller: App\Controller\BailController::listerContratLocation

# LISTER MODIFIER CONTRAT DE LOCATION
contratLocationListerModifier:
    path: /baux/listerModifierContratLocation
    controller: App\Controller\BailController::listerModifierContratLocation

# FORM MODIFIER CONTRAT DE LOCATION
contratLocationModifier:
    path: /baux/modifierContratLocation/{id}
    controller: App\Controller\BailController::modifierContratLocation

# LISTER CLOTURER CONTRAT DE LOCATION
contratLocationListerCloturer:
    path: /baux/listerCloturerContratLocation
    controller: App\Controller\BailController::listerCloturerContratLocation

# FORM CLOTURER CONTRAT DE LOCATION
contratLocationCloturer:
    path: /baux/cloturerContratLocation/{id}
    controller: App\Controller\BailController::cloturerContratLocation

# LISTER CONTRAT DE LOCATION ARCHIVES
contratLocationArchivesLister:
    path: /baux/listerContratLocationArchives
    controller: App\Controller\BailController::listerContratLocationArchives

# PDF CONTRAT DE LOCATION
contratLocationPDF:
    path: /baux/{id}/contratLocation
    controller: App\Controller\BailController::contratLocationPDF

# AJOUTER LOCATAIRE
ajouterLocataire:
    path: /locataire/ajouter
    controller: App\Controller\LocataireController::ajouterLocataire

# CONSULTER LOCATAIRE
locataireConsulter:
    path: /locataire/consulter/{id}
    controller: App\Controller\LocataireController::consulterLocataire

# NOUVEAU VERSEMENT
versement:
    path: /paiement/versement
    controller: App\Controller\PaiementController::versement

# AJOUTER CATEGORIE
ajouterCategorie:
    path: /admin/ajouterCategorie
    controller: App\Controller\AdminController::ajouterCategorie

# LISTER CATEGORIE
listerCategorie:
    path: /admin/listerCategorie
    controller: App\Controller\AdminController::listerCategorie

# MODIFIER CATEGORIE
modifierCategorie:
    path: /admin/modifierCategorie/{id}
    controller: App\Controller\AdminController::modifierCategorie

# AJOUTER SOUS-CATEGORIE
ajouterSousCategorie:
    path: /admin/ajouterSousCategorie
    controller: App\Controller\AdminController::ajouterSousCategorie

# LISTER SOUS-CATEGORIE
listerSousCategorie:
    path: /admin/listerSousCategorie
    controller: App\Controller\AdminController::listerSousCategorie

# MODIFIER SOUS-CATEGORIE
modifierSousCategorie:
    path: /admin/modifierSousCategorie/{id}
    controller: App\Controller\AdminController::modifierSousCategorie

# AJOUTER ASSOCIE
ajouterAssocie:
    path: /associe/ajouter
    controller: App\Controller\AssocieController::ajouterAssocie

# CONSULTER ASSOCIE
consulterAssocie:
    path: /associe/consulter/{id}
    controller: App\Controller\AssocieController::consulterAssocie

# LISTER ASSOCIE
associeLister:
    path: /associe/lister
    controller: App\Controller\AssocieController::listerAssocie

# PROFIL USER
userProfil:
    path: /user/profil
    controller: App\Controller\UserController::profil