controllers:
    resource: ../src/Controller/
    type: attribute

# ACCUEIL
route_accueil:
    path: /accueil
    controller: App\Controller\BailController::index

# AJOUTER BAIL
ajouterBail:
    path: /baux/ajouter
    controller: App\Controller\BailController::ajouterBail

# LISTER BAUX
bauxLister:
    path: /baux/lister
    controller: App\Controller\BailController::listerBaux

# CONSULTER BAUX
bauxConsulter:
    path: /baux/consulter/{id}
    controller: App\Controller\BailController::consulterBaux

# LISTER PAIEMENT
paiementLister:
    path: /paiement/listerLoyer
    controller: App\Controller\PaiementController::listerLoyer

# LISTER MOUVEMENT
mouvementLister:
    path: /mouvement/lister
    controller: App\Controller\MouvementController::listerMouvement

# UPLOAD FILE MOUVEMENT
mouvementUploadFile:
    path: /mouvement/uploadFile
    controller: App\Controller\MouvementController::uploadFileMouvement

# MODIFIER MOUVEMENT
modifierMouvement:
    path: /mouvement/modifier/{id}
    controller: App\Controller\MouvementController::modifierMouvement

# PDF QUITTANCE
quittancePDF:
    path: /baux/{id}/quittance
    controller: App\Controller\BailController::quittancePDF

# CONSULTER APPARTEMENT
appartementConsulter:
    path: /appartement/consulter/{id}
    controller: App\Controller\AppartementController::consulterAppartement