controllers:
    resource: ../src/Controller/
    type: attribute

# ACCUEIL
accueil:
    path: /accueil
    controller: App\Controller\BailController::index

# AJOUTER BAIL
ajouterBail:
    path: /baux/ajouter
    controller: App\Controller\BailController::ajouterBail

# LISTER BAUX
bauxLister:
    path: /baux/lister
    controller: App\Controller\BailController::listerBaux

# LISTER BAUX ARCHIVES
bauxArchivesLister:
    path: /baux/listerBauxArchives
    controller: App\Controller\BailController::listerBauxArchives

# CONSULTER BAUX
bauxConsulter:
    path: /baux/consulter/{id}
    controller: App\Controller\BailController::consulterBaux

# LISTER PAIEMENT
paiementLister:
    path: /paiement/listerLoyer
    controller: App\Controller\PaiementController::listerLoyer

# LISTER MOUVEMENT
mouvementLister:
    path: /mouvement/lister
    controller: App\Controller\MouvementController::listerMouvement

# UPLOAD FILE MOUVEMENT
mouvementUploadFile:
    path: /mouvement/uploadFile
    controller: App\Controller\MouvementController::uploadFileMouvement

# MODIFIER MOUVEMENT
modifierMouvement:
    path: /mouvement/modifier/{id}
    controller: App\Controller\MouvementController::modifierMouvement

# PDF QUITTANCE
quittancePDF:
    path: /baux/{id}/quittance
    controller: App\Controller\BailController::quittancePDF

# CONSULTER APPARTEMENT
appartementConsulter:
    path: /appartement/consulter/{id}
    controller: App\Controller\AppartementController::consulterAppartement

# LISTER CONTRAT DE LOCATION
contratLocationLister:
    path: /baux/listerContratLocation
    controller: App\Controller\BailController::listerContratLocation

# LISTER CONTRAT DE LOCATION ARCHIVES
contratLocationArchivesLister:
    path: /baux/listerContratLocationArchives
    controller: App\Controller\BailController::listerContratLocationArchives

# PDF CONTRAT DE LOCATION
contratLocationPDF:
    path: /baux/{id}/contratLocation
    controller: App\Controller\BailController::contratLocationPDF

# AJOUTER LOCATAIRE
ajouterLocataire:
    path: /locataire/ajouter
    controller: App\Controller\LocataireController::ajouterLocataire

# CONSULTER LOCATAIRE
locataireConsulter:
    path: /locataire/consulter/{id}
    controller: App\Controller\LocataireController::consulterLocataire

# NOUVEAU VERSEMENT
versement:
    path: /paiement/versement
    controller: App\Controller\PaiementController::versement
